### PR TITLE
HLT menu v4

### PR DESCRIPTION
**Pull request by silviodonato**
Sub-tables for the first version of the HLT menu V4

### CODE REVIEW

**Comment by silviodonato** [comment]
@perrotta  @Martin-Grunewald , could you add me to cms-tsg-storm?
Thanks, Silvio.

**Comment by Martin-Grunewald** [comment]
@fwyzard 
Can you please add @silviodonato to cms-tsg-strom github?

Thanks!

**Comment by Martin-Grunewald** [comment]
@silviodonato 
We'd need the PR also for the 81X branch

**Comment by Martin-Grunewald** [comment]
@silviodonato
FastSim seems broken. Did you run our test suite?

**Comment by Martin-Grunewald** [comment]
Hi,

I think we need for fastsim at least:

```
diff --git a/HLTrigger/Configuration/python/customizeHLTforMC.py b/HLTrigger/Con
index 7306c6c..01f010e 100644
--- a/HLTrigger/Configuration/python/customizeHLTforMC.py
+++ b/HLTrigger/Configuration/python/customizeHLTforMC.py
@@ -245,6 +245,7 @@ def customizeHLTforMC(process,_fastSim=False):
       "hltPixelLayerTripletsReg",
       "hltPixelLayerTripletsHITHB",
       "hltPixelLayerTripletsHITHE",
+      "hltPixelLayerTripletsAfterSplitting",
       "hltMixedLayerPairs",

       "hltFastPrimaryVertexbbPhi",
@@ -288,6 +289,8 @@ def customizeHLTforMC(process,_fastSim=False):
       "HLTDoLocalStripSequenceRegForBTag",
       "HLTDoLocalPixelSequenceRegForBTag",
       "HLTDoLocalPixelSequenceRegForNoPU",
+      "HLTDoLocalPixelSequenceAfterSplitting",
+      "HLTPADoLocalStripSequenceAfterSplitting",
       "HLTBeginSequence",
       "HLTBeginSequenceL1Fat",
       "HLTBeginSequenceNZS",
@@ -495,6 +498,7 @@ def customizeHLTforMC(process,_fastSim=False):
       ('hltOfflineBeamSpot','offlineBeamSpot'),
       ('hltOnlineBeamSpot','offlineBeamSpot'),
       ('hltSiStripClusters','MeasurementTrackerEvent'),
+      ('hltSiStripClustersAfterSplitting','MeasurementTrackerEvent'),

       )
     from HLTrigger.Configuration.CustomConfigs import MassReplaceInputTag
```

but there is still a crash left....

**Pull request merged**
